eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-provider
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
      uri: http://localhost:8888/

  # 集成 rabbitMQ
#  rabbitmq:
#    host:
#    port:
#    username:
#    password:



server:
  port: 8084

# spring boot 1.5 之前是这样
# 关闭刷新安全认证
# management.security.enabled=false

# spring boot 2.0 后 需要暴露actuator的所有端口
# 发送 POST  http://localhost:8084/actuator/refresh  刷新配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
