spring:
  application:
    name: zuul-service

server:
  port: 9000


#  路由转发
#zuul:
#  routes:
#    xinchen:
#      path: /
#      url: https://melodyfff.github.io/


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#  浏览器访问:http://127.0.0.1:9000/ ,Zuul 会去 Eureka 服务注册中心，找到eureka-provider服务以均衡负载的方式访问
zuul:
  routes:
    api:
      path: /**
      serviceId: eureka-provider
